apiVersion: apps/v1
kind: Deployment
metadata:
  name: meine-test-app
spec:
  replicas: 5 #32
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest

# RunID: 639189719261197207
